services:
  redis:
    image: redis:7-alpine
    container_name: redis-parcel-${CONFIG_NAME}
    restart: always
    networks:
      parcel_network:
        aliases:
          - redis-parcel-${CONFIG_NAME}

  web:
    image: ${DOCKERHUB_USERNAME}/parcel-service:${TAG}
    container_name: parcel-service-${CONFIG_NAME}
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    command: >
       gunicorn -c gunicorn.conf.py run:app
    networks:
      - parcel_network

  template-service:
    image: ${DOCKERHUB_USERNAME}/template-service:latest
    container_name: template-service-parcel-${CONFIG_NAME}
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    networks:
      - parcel_network

volumes:
  redis-master-data:

networks:
  parcel_network:
    external: true
